server.port=1011
spring.application.name=hz01-frontend

# Backend API base URL
hz01.backend.url=http://localhost:8000

# Vaadin
vaadin.launch-browser=true
vaadin.allowed-packages=com.vaadin,org.vaadin,dev.hilla,com.hz01

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false
